= PHPカンファレンス2015感想など
:hp-alt-title: phpconf2015_impression
:hp-tags: PHP

SQLインジェクションの開発会社への判決
2009講演資料　発注者側に責任（当時判例無し）

家具インテリアECサイト侵入事件
ECサイトからクレカ情報が盗まれた
X社（原告）は特にセキュリティに明示無し
損害賠償責任制限があり

個人情報を含むログファイルが外部から閲覧可能

地裁判決
Y社（被告）にはセキュリティ対策を講じる義務を認めた
損害賠償責任制限は上記の義務を満たさなかったため重過失認定
控訴断念のため確定判決

判決文の換装
専門家としての責務を果たしていない点を司法は重視した

考察
開発会社は脆弱性対策の「安全なウェブサイトの作り方」ぐらいは最低限対策する

入門書向けSQLインジェクション対策の状況
入門書の時点で学んでおいた方が後で学習し直すコストの削減

結構前の入門書
? と AAA が与えられると誤動作
SELECT * FROM foo WHERE bar=? AND baz=?
OR 1=1-- で死ぬ
プレースホルダは自作しない

少し前の入門書
少しは考慮されるようになったが依然脆弱性が存在
プレースホルダではなくエスケープを使うとすごい難しいので脆弱性が生まれやすい
DELETE 文で個人情報が漏れる
1ビットずつブラインドSQLインジェクションで個人情報取り出す事が出来る

2年前の入門書
SQLインジェクションは一応対策されている

最近の状況
PDOとプレースホルダが鉄板
XSSやXSRFは不十分

SQLインジェクション対策
プレースホルダ
文字エンコーディング指定はパラメータで

サンプルコード
例外は定数指定
型を指定してバインド

O/RマッパーとSQLジェネレーター

Rails SQL Injection Examples
https://rails-sqli.org/
アプリ側での悪い例が載っている

UNION SELECTで別のテーブルの情報を持ってこれる

Zend Frameworkでも同様

Postgresql
Rail で ORDER BY を呼び出す関数は式がかける
SQLインジェクションが容易に起こせる

ORDER BY と UNION の攻撃は複文で AS の 別名を使用すれば盗まれる

対策
一番簡単なのはバリデーション

Zend Frameworkでも同様な脆弱性
order メソッドで式がかける
文字列と式の判別が適当
徳丸先生どん引きレベルで
根本的に仕様がまずい

識別仕様のメソッドと式用のメソッドを分ける

JSON SQLインジェクション
Perl の SQL::Maker
渡される値で演算子があるとエスケープやバリデーションされない

PHP版のSQL::Maker
同様の問題がある
JSONを渡さなくても、$_GET や $_POST でも攻撃される
文字列が来るところに配列が来るのが問題

Drupageddon
Drupal 7.31以前の問題
db_query 関数
連想配列を渡す そのまま
キーを渡す そのまま
空白を渡す そのまま

name[2 ;SELECT sleep(10)]=xxx&name[2]
Burp Suiteで書き換え

Create New Accountからアカウント作成
Roleを与える

質疑応答
開発会社賠償の件
EC cube自体ではない（おそらく、カスタマイズ部分）
本体が脆弱性あるの場合はまだ不明

パッチ適用も提案して記録を残す（蹴られたら発注側にも責任が出てくると思われる）

「安全なウェブサイトの作り方」や専門書で注意喚起がなされたものは対応した方が良い

O/Rマッパー
ORDER BY に式を立てられるものはSQLのミドルウェア依存なのか？
O/Rマッパーによる抽象化は脆弱性対策でどこまで対策すれば良いか
原理原則に忠実に

MySQL 5.7にやられないために知っておいてほしいこと
MySQL 5.7で入った機能を安易に使用しない
罠は事前に調べておく

徳丸先生に怒られない動的SQLの組み方
SQLインジェクションの賠償
賠償金 5000万円〜1億円程度

考察
SQLインジェクションがなぜ発生するか
エスケープ、プレースホルダは必須

スキルが追いついていない人への教育をどうするか？

原因：
文字列連結でSQLを組み立てるから
対策；SQLテンプレート、SQL構文木

推定
プレースホルダでしづらい事があるから

原因2：
SQLを文字列で指定できてしまうから

対策；SQL ID、SQL構文木

ライブラリ、APIの I/F に欠陥があることが問題

SQLテンプレート
SQLを生成するためのテンプレート
原理上はSQLインジェクションが起きない

テンプレートエンジン例
SQLTempl8

原理上はSQLインジェクションが起きない理由
文字列連結できない
変数展開が出来ない

IS NULLは
MySQL: <=>演算子
PostgreSQL: IS NOT DISTINCT FROM 演算子
を使用する

SQL構文木
O/R マッパー

構文木なら SQL文字列を作成できる

SQL構文木は脆弱性を呼ぶような文字列が渡されても、木構造を変えるわけではないので問題ない

実は、HTMLテンプレートエンジンでは既知の内容だった

いまどきのPHP開発現場 2015秋
ツール
Github + Travis CI + Heroku + Slack

PHPStorm
Vagrant
・プロジェクト毎に独立した環境
・自動構築
・チームで同じ環境を利用
・運用環境と同じ環境

導入ポイント
・PHPコードと一緒に管理
・とことん自動化（vagrant upで完了）
Ansible 関係
・プロビジョニングはVMの中で実行
・Shell Script->Ansible

フレームワーク
コンポーネント指向が主流

Laravel
Symfony コンポーネントを多数利用
いいとこ取り
Laravelもコンポーネントとして利用可能

フレームワークの付き合い方
・フレームワークに従うのではなくアプリケーションの部品として使う
・フレームワーク on フレームワーク
・インハウスフレームワーク （本当に独自の部分だけ自作フレームワーク）

CIサーバ、サービス
テスト実行、フォーマットチェック、静的解析

Travis CI
GitHubとのみ連携
.travis.yml に記述していく

Scrutinizer
コードフォーマットや静的解析のSaaS
Travis CIと組み合わせ

PaaS
Herokuが、PHPを正式サポート(2014)

まとめ
ツールやサービスに任せる
やるべきことに集中
ツールに導かれる（正しく使う）

脆弱性もバグ
テストの普及
・セキュリティテスト


・パフォーマンステスト
loader.io


セキュリティテスト
・ホワイトボックス
Brakeman(Rails)、Parse(PHP)

・ブラックボックス
攻撃用HTTPリクエストを投げる
App Scan

現状の問題点
リリース直前に大量の脆弱性発見

理想
開発初期からテストする

継続的ウェブセキュリティテスト

課題
既存のツールの場合


重要な点
アプリケーションの動作は把握しておかないといけない
ログイン周り
エラー画面へのチェックを誤って行う

Vaddy

LT
ランダムデータ作成
generatedate
Faker
Fabricate